### ISSUE TITLE
Provide links to weights, training, validation and test used in e.g. pytoach examples

### ISSUE THREAD

**Issue by GeorgeS2019** [Bakaczor/InceptionResidualNet#1]
```
private static readonly string _weightsSavePath = @".\weights.bin";
private static readonly string _trainLoadPath = @".\dataset\training";
private static readonly string _validationLoadPath = @".\dataset\validation";
private static readonly string _testLoadPath = @".\dataset\test";
```

**Comment by Bakaczor** [comment]
What kind of links do you expect? The dataset we used for the project was taken from Kaggle, if I recall it could have been [this one](https://www.kaggle.com/datasets/shanmukh05/agedetection/data). The path for the weights is provided via CLI:
```csharp
string? weights = args.Length > 0 ? args[0] : null;
if (weights != null) {
    Console.WriteLine("\tWeights loaded...");
} else {
    Console.WriteLine("\tWeights not loaded...");
}
```
If provided, the model will load and try to improve the weights:
```csharp
if (weights != null) {
     model.load(weights);
}
```
If not, it will create a new file at the default location:
```csharp
private static readonly string _weightsSavePath = @".\weights.bin";
```
If it doesn't anwser you question, try to make it more precise or refer to the [examples in the documentation](https://github.com/dotnet/TorchSharpExamples/blob/main/tutorials/CSharp/README.md).
